### PR TITLE
add access control view

### PR DESCRIPTION
**Pull request by wei-lee**
This PR:

* add the access control view to show what roles the logged user has
* improve the authentication view so that the user details view is displayed is the user is already logged in
* change the api server url

ping @TommyJ1994

### CODE REVIEW

**Comment by tomjackman** [comment]
Just noticed that the user details screen doesn't update if you login as one user, then logout and login as another user. It just displays the old users data. Doesn't look like it's related to this change, but something I noticed when checking the roles of different users etc.

**Comment by tomjackman** [comment]
Looks good. Maybe we can add a small popup when you visit the access control screen to say that you must first be authenticated and possess the `mobile-user` role before you can access the view. Just might provide more info over a redirect to the auth screen.

**Comment by wei-lee** [comment]
@TommyJ1994 that bug is fixed now. I have also added tests to cover the case. See 89ac397875f54f9cfa158e699a12916a8ceb4cce

**Review by tomjackman — APPROVED** [review]
Looks good. Tests look good and run successfully.

**Pull request merged**
